version: "3.8"

services:
  dockge:
    image: louislam/dockge:latest
    container_name: dockge
    restart: unless-stopped
    ports:
      - "8081:5001"          # internal UI, reverse proxy in front later
    environment:
      - DOCKGE_STACKS_DIR=/stacks
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/verkamaedhr/docker/dockge/stacks:/stacks
      - /mnt/verkamaedhr/docker/dockge/data:/app/data
